### ISSUE TITLE
文档好像有几个错别字。。。。。

### ISSUE THREAD

**Issue by stateIs0** [alipay/sofa-rpc-node#2]
<img width="902" alt="sofa0-nodojs" src="https://user-images.githubusercontent.com/24973360/40759570-29b34948-64c5-11e8-8d5c-55da7f8eb568.png">

`这块也会再近期开放，尽情期限！`

这块也会在近期开放，敬请期待？

不知道理解的对不对哈 ：）

**Comment by gxcsoccer** [comment]
谢谢反馈，你理解的对 👍

**Comment by gxcsoccer** [comment]
https://github.com/alipay/sofa-rpc-node/pull/3
